name: Code Review with OpenAI
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: SectorLabs/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REVIEW_SHOULD_USER_PR_DESCRIPTION: false
          REVIEW_MIN_FILE_LINE_CHANGES: 10
          REVIEW_MAX_COMMENTS: 3
          exclude: "yarn.lock,dist/**"
